x-default: &default
  restart: unless-stopped
  volumes:
    - &localtime /etc/localtime:/etc/localtime:ro
    - &timezone /etc/timezone:/etc/timezone:ro
  logging:
    driver: json-file
    options:
      max-size: 1m

services:
  app:
    <<: *default
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8098:8000
